version: '3'
services:
  database:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    env_file:
      - database.env
    volumes:
      - 'database-data:/var/lib/postgresql/data/'

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    image: frontend_test
    ports:
      - '80:80'
    depends_on:
      - database
      - storage
      - backend

  backend:
    build:
      context: backend
      target: debug
      dockerfile: Dockerfile.debug
    image: backend_test
    ports:
      - "2345:2345" # for delve remote debugging
      - "8080:8080"
    env_file:
      - backend.env
    security_opt:
      - "seccomp:unconfined"
    volumes:
      - ./:/app
    depends_on:
      - database
      - storage

  storage:
    image: minio/minio
    volumes:
      - 'imgstore-data:/data1'
    ports:
      - '9000:9000'
    env_file:
      - minio.env
    command: server /data1
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://localhost:9000/minio/health/live'
      interval: 30s
      timeout: 20s
      retries: 3

  adminer.imgprocessing.io:
    image: adminer:4-standalone
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - database

volumes:
  database-data: null
  imgstore-data: null
