# GO Repo base repo
FROM golang:alpine as builder

RUN apk --no-cache add ca-certificates curl
RUN apk add build-base
RUN apk add inotify-tools

COPY . /debug_env

WORKDIR /debug_env

RUN go mod download

RUN go get github.com/go-delve/delve/cmd/dlv

CMD sh /debug_env/run.sh