version: '3'
services:
  database:
    image: 'postgres:latest'
    restart: always
    env_file:
      - database.env
    volumes:
      - 'database-data:/var/lib/postgresql/data/'
    networks:
      - database

  frontend:
    image: 'ghcr.io/imgprocessing/frontend:latest'
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend-http.rule=Host(`${COMPOSE_SITE_NAME}`)
      - traefik.http.routers.frontend-http.entrypoints=http
      - traefik.http.routers.frontend-http.middlewares=redirect
      - traefik.http.routers.frontend-https.rule=Host(`${COMPOSE_SITE_NAME}`)
      - traefik.http.routers.frontend-https.entrypoints=https
      - traefik.http.routers.frontend-https.tls=true
      - traefik.http.services.frontend.loadbalancer.server.port=80
      - traefik.http.services.frontend.loadbalancer.healthcheck.interval=5s
      - traefik.http.services.frontend.loadbalancer.healthcheck.timeout=2s
      - traefik.http.middlewares.redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.redirect.redirectscheme.permanent=true
      - traefik.docker.network=${COMPOSE_PROJECT_NAME}_frontend
    networks:
      - frontend
    depends_on:
      - loadbalancer
      - backend

  backend:
    image: 'ghcr.io/imgprocessing/backend:latest'
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.backend-http.rule=Host(`${COMPOSE_SITE_NAME}`) && PathPrefix(`/api`)
      - traefik.http.routers.backend-http.entrypoints=http
      - traefik.http.routers.backend-http.middlewares=redirect
      - traefik.http.routers.backend-https.rule=Host(`${COMPOSE_SITE_NAME}`) && PathPrefix(`/api`)
      - traefik.http.routers.backend-https.entrypoints=https
      - traefik.http.routers.backend-https.tls=true
      - traefik.http.services.backend.loadbalancer.server.port=8080
      - traefik.http.services.backend.loadbalancer.healthcheck.interval=5s
      - traefik.http.services.backend.loadbalancer.healthcheck.timeout=2s
      - traefik.http.middlewares.redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.redirect.redirectscheme.permanent=true
      - traefik.docker.network=${COMPOSE_PROJECT_NAME}_backend
    networks:
      - backend
      - storage
      - database
    depends_on:
      - database
      - storage
      - loadbalancer

  loadbalancer:
    image: traefik
    restart: always
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - '${PWD}/infrastructure/traefik.toml:/etc/traefik/traefik.toml'
      - '${PWD}/infrastructure/ssl.toml:/etc/traefik/ssl.toml'
      - '${PWD}/infrastructure/ssl:/etc/certs'
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    networks:
      - backend
      - frontend
      - loadbalancer

  storage:
    image: minio/minio
    restart: always
    volumes:
      - 'imgstore-data:/data1'
    expose:
      - '9000'
    env_file:
      - minio.env
    command: server /data1
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://localhost:9000/minio/health/live'
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - storage

networks:
  loadbalancer:
    internal: false
  frontend:
    internal: true
  backend:
    internal: true
  database:
    internal: true
  storage:
    internal: true
    
volumes:
  database-data: null
  imgstore-data: null
