[tls]

[tls.stores]

[tls.stores.default]

[tls.stores.default.defaultCertificate]
certFile = "/etc/certs/cert.pem"
keyFile = "/etc/certs/key.pem"

[[tls.certificates]]
certFile = "/etc/certs/cert.pem"
keyFile = "/etc/certs/key.pem"
stores = ["default"]